name: Bug report
description: Let us know about an unexpected error, a crash, or an incorrect behavior.
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Before submitting this issue, please check the open issues and ensure that you fill in as much as possible in this template.
        📝 If including build failures, or general tool output, please ensure they are in English, i.e. `LC_ALL=C LANG=C`.
        📝 If your issue is a Budgie *crash*, include a stack trace. (gdb)

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the issue you encountered.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Budgie version
      description: To provide the exact version of your Budgie installation, run `budgie-desktop --version`.
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Name and version number of your Operating System.
      placeholder: Solus 4
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the issue
      description: Please add the steps on how to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: actual-result
    attributes:
      label: Actual result
      description: Please add screenshots if needed.
    validations:
      required: true

  - type: textarea
    id: expected-result
    attributes:
      label: Expected result
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
