.TH BUDGIE\-BRIGHTNESS\-HELPER "1" "January 2026" "budgie-brightness-helper" "User Commands"
.SH NAME
budgie\-brightness\-helper \- helper for adjusting display brightness
.SH SYNOPSIS
.B budgie\-brightness\-helper
\fI\,<command>\/\fR [\fI\,value\/\fR]
.SH DESCRIPTION
.B budgie\-brightness\-helper
adjusts the display brightness level.
.SH COMMANDS
.TP
.B up [\fIstep\fR]
Increase brightness by \fIstep\fR percent (default: 5).
.TP
.B down [\fIstep\fR]
Decrease brightness by \fIstep\fR percent (default: 5).
.TP
.B set \fIvalue\fR
Set brightness to a specific percentage (0\-100).
.SH EXAMPLES
.TP
.B budgie\-brightness\-helper up
Increase brightness by 5%.
.TP
.B budgie\-brightness\-helper up 10
Increase brightness by 10%.
.TP
.B budgie\-brightness\-helper down
Decrease brightness by 5%.
.TP
.B budgie\-brightness\-helper set 50
Set brightness to 50%.
